### ISSUE TITLE
Errors at set up

### ISSUE THREAD

**Issue by CamilingJS** [epicweb-dev/full-stack-foundations#33]
I getting these errors at  npm run setup

npm ERR! code EISDIR
npm ERR! syscall symlink
npm ERR! path E:\EpicWeb\full-stack-foundations\exercises\07.error-handling\05.solution.not-found
npm ERR! dest E:\EpicWeb\full-stack-foundations\node_modules\exercises__sep__07.error-handling__sep__05.solution.not-found
npm ERR! errno -4068
npm ERR! EISDIR: illegal operation on a directory, symlink 'E:\EpicWeb\full-stack-foundations\exercises\07.error-handling\05.solution.not-found' -> 'E:\EpicWeb\full-stack-foundations\node_modules\exercises__sep__07.error-handling__sep__05.solution.not-found'

**Comment by kentcdodds** [comment]
Hi @CamilingJS!

Sorry you're having issues! Try to run the setup with admin privileges to resolve symlink issues. If you're on Windows, right-click your command prompt and "Run as Administrator", then rerun `npm run setup`.

Details: The error `EISDIR: illegal operation on a directory, symlink` typically occurs due to a lack of permission to create symbolic links, which can happen on Windows systems. Running the command prompt as an administrator should resolve this. If it doesn't, you might want to look into using WSL2 on Windows for a more Unix-like environment.

I hope that helps get you unstuck.

**Comment by CamilingJS** [comment]
> Hi @CamilingJS!
> 
> Sorry you're having issues! Try to run the setup with admin privileges to resolve symlink issues. If you're on Windows, right-click your command prompt and "Run as Administrator", then rerun `npm run setup`.
> 
> Details: The error `EISDIR: illegal operation on a directory, symlink` typically occurs due to a lack of permission to create symbolic links, which can happen on Windows systems. Running the command prompt as an administrator should resolve this. If it doesn't, you might want to look into using WSL2 on Windows for a more Unix-like environment.
> 
> I hope that helps get you unstuck.

Unfortunately, running with admin privileges didn't work. I'll look into WSL2.

**Comment by CamilingJS** [comment]
I've ran it as Administrator and with WSL, updated latest node and npm and unfortunately still getting the same errors.
I'll continue researching. 

npm ERR! code EISDIR
npm ERR! syscall symlink
npm ERR! path E:\Remix-Training\Epic-Web\full-stack-foundations\exercises\07.error-handling\05.solution.not-found
npm ERR! dest E:\Remix-Training\Epic-Web\full-stack-foundations\node_modules\exercises__sep__07.error-handling__sep__05.solution.not-found
npm ERR! errno -4068
npm ERR! EISDIR: illegal operation on a directory, symlink 'E:\Remix-Training\Epic-Web\full-stack-foundations\exercises\07.error-handling\05.solution.not-found' -> 'E:\Remix-Training\Epic-Web\full-stack-foundations\node_modules\exercises__sep__07.error-handling__sep__05.solution.not-found'

npm ERR! A complete log of this run can be found in: C:\Users\jonat\AppData\Local\npm-cache\_logs\2023-10-22T23_56_53_981Z-debug-0.log
    🚨  Failure: Dependency Installation. Please review the messages above for information on how to troubleshoot and resolve this issue.

**Comment by kentcdodds** [comment]
Dang, I was hoping that would work. I'm afraid I really don't know what could be the cause here. I've never seen this issue before and I know many other people are running this successfully. I'm sorry you're having so many issues :(

**Comment by kentcdodds** [comment]
As a workaround, I just tested out running the workshop using GitHub Codespaces and it does work if you want to give that a shot https://github.com/codespaces

You can even login and everything. The only issue is the port forwarding doesn't work quite as well and you can't open the `playground` directory in its own instance of the editor so it's a little harder to navigate (the links that open files in your editor won't work either). But that could get you unstuck if you can't find a way to run things locally.

I hope that helps!
